# Generated by Django 2.2.13 on 2020-12-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.PositiveIntegerField()),
                ('cid', models.PositiveIntegerField()),
                ('qid', models.PositiveIntegerField()),
                ('updatetime', models.DateTimeField(null=True)),
                ('user', models.CharField(max_length=200)),
                ('cdescription', models.TextField(null=True)),
                ('sentiments', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.PositiveIntegerField()),
                ('skuname', models.CharField(max_length=200)),
                ('updatetime', models.DateTimeField(null=True)),
                ('skuurl', models.URLField()),
                ('pricescript', models.CharField(max_length=50, null=True)),
                ('skudescription', models.TextField(null=True)),
                ('worthy', models.PositiveIntegerField(null=True)),
                ('notworthy', models.PositiveIntegerField(null=True)),
                ('stars', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
